version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "08:00"
      timezone: "Europe/London"
    target-branch: "dependency-updates"
    open-pull-requests-limit: 20
