version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - cd Parking.Service
      - dotnet lambda deploy-function --function-name $SERVICE_FUNCTION_NAME
      - cd ../Parking.Api
      - dotnet lambda deploy-function --function-name $API_FUNCTION_NAME