name: Run tests
env:
  DATA_BUCKET_NAME: parking-data
  TRIGGER_BUCKET_NAME: parking-trigger
  TABLE_NAME: parking-table
  TOPIC_NAME: arn:aws:sns:eu-west-2:0123456789ab:parking-notifications

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  run-tests:

    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          DEFAULT_REGION: eu-west-2
          SERVICES: dynamodb,s3,ses,sns

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: API unit tests
      run: dotnet test Parking.Api.UnitTests/Parking.Api.UnitTests.csproj
    - name: Business unit tests
      run: dotnet test Parking.Business.UnitTests/Parking.Business.UnitTests.csproj
    - name: Data unit tests
      run: dotnet test Parking.Data.UnitTests/Parking.Data.UnitTests.csproj
    - name: API integration tests
      run: dotnet test Parking.Api.IntegrationTests/Parking.Api.IntegrationTests.csproj
